export const Relics = {
  100: { name: "delicateBurningScene", color: "red", type: "relic" },
  101: { name: "polishedBurningScene", color: "red", type: "relic" },
  102: { name: "grandBurningScene", color: "red", type: "relic" },
  103: { name: "delicateBurningScene", color: "red", type: "relic" },
  104: { name: "polishedBurningScene", color: "red", type: "relic" },
  105: { name: "grandBurningScene", color: "red", type: "relic" },
  106: { name: "delicateBurningScene", color: "red", type: "relic" },
  107: { name: "polishedBurningScene", color: "red", type: "relic" },
  108: { name: "grandBurningScene", color: "red", type: "relic" },
  109: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  110: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  111: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  112: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  113: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  114: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  115: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  116: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  117: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  118: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  119: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  120: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  121: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  122: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  123: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  124: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  125: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  126: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  127: { name: "delicateTranquilScene", color: "green", type: "relic" },
  128: { name: "polishedTranquilScene", color: "green", type: "relic" },
  129: { name: "grandTranquilScene", color: "green", type: "relic" },
  130: { name: "delicateTranquilScene", color: "green", type: "relic" },
  131: { name: "polishedTranquilScene", color: "green", type: "relic" },
  132: { name: "grandTranquilScene", color: "green", type: "relic" },
  133: { name: "delicateTranquilScene", color: "green", type: "relic" },
  134: { name: "polishedTranquilScene", color: "green", type: "relic" },
  135: { name: "grandTranquilScene", color: "green", type: "relic" },
  1000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1010: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1020: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1030: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1040: { name: "polishedBurningScene", color: "red", type: "relic" },
  1050: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1060: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1070: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1080: { name: "polishedBurningScene", color: "red", type: "relic" },
  1090: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1100: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1110: { name: "polishedBurningScene", color: "red", type: "relic" },
  1120: { name: "polishedBurningScene", color: "red", type: "relic" },
  1130: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1140: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1150: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1160: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1170: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1180: { name: "grandBurningScene", color: "red", type: "relic" },
  1190: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1200: { name: "grandTranquilScene", color: "green", type: "relic" },
  1210: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1220: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1230: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1240: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1250: { name: "grandBurningScene", color: "red", type: "relic" },
  1260: { name: "grandBurningScene", color: "red", type: "relic" },
  1270: { name: "grandTranquilScene", color: "green", type: "relic" },
  1400: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1410: { name: "grandBurningScene", color: "red", type: "relic" },
  1420: { name: "grandTranquilScene", color: "green", type: "relic" },
  1430: { name: "grandTranquilScene", color: "green", type: "relic" },
  1440: { name: "grandBurningScene", color: "red", type: "relic" },
  1450: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1460: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1470: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1480: { name: "grandBurningScene", color: "red", type: "relic" },
  1490: { name: "grandTranquilScene", color: "green", type: "relic" },
  1500: { name: "grandBurningScene", color: "red", type: "relic" },
  1510: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1520: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  2000: { name: "nightOfTheBeast", color: "green", type: "unique" },
  2001: { name: "darkNightOfTheBeast", color: "yellow", type: "unique" },
  2010: { name: "nightOfTheBaron", color: "blue", type: "unique" },
  2011: { name: "darkNightOfTheBaron", color: "red", type: "unique" },
  2020: { name: "nightOfTheWise", color: "yellow", type: "unique" },
  2021: { name: "darkNightOfTheWise", color: "green", type: "unique" },
  2030: { name: "nightOfTheFathom", color: "red", type: "unique" },
  2031: { name: "darkNightOfTheFathom", color: "blue", type: "unique" },
  2040: { name: "nightOfTheDemon", color: "red", type: "unique" },
  2041: { name: "darkNightOfTheDemon", color: "blue", type: "unique" },
  2050: { name: "nightOfTheChampion", color: "green", type: "unique" },
  2051: { name: "darkNightOfTheChampion", color: "yellow", type: "unique" },
  2060: { name: "nightOfTheMiasma", color: "yellow", type: "unique" },
  2061: { name: "darkNightOfTheMiasma", color: "green", type: "unique" },
  2100: { name: "nightOfTheLord", color: "blue", type: "unique" },
  10000: { name: "oldPocketwatch", color: "green", type: "unique" },
  10001: { name: "besmirchedFrame", color: "blue", type: "unique" },
  10002: { name: "fellOmenFetish", color: "blue", type: "unique" },
  11000: { name: "slateWhetstone", color: "red", type: "unique" },
  11001: { name: "theWyldersEarring", color: "red", type: "unique" },
  11002: { name: "silverTear", color: "red", type: "unique" },
  11003: { name: "delicateBurningScene", color: "red", type: "relic" },
  11004: { name: "delicateBurningScene", color: "red", type: "relic" },
  12000: { name: "thirdVolume", color: "red", type: "unique" },
  12001: { name: "stoneStake", color: "red", type: "unique" },
  12002: { name: "witchsBrooch", color: "blue", type: "unique" },
  12003: { name: "crackedWitchsBrooch", color: "blue", type: "unique" },
  12004: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  12005: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  12006: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  12007: { name: "delicateTranquilScene", color: "green", type: "relic" },
  13001: { name: "crackedSealingWax", color: "yellow", type: "unique" },
  13002: { name: "edgeOfOrder", color: "yellow", type: "unique" },
  14000: { name: "goldenDew", color: "yellow", type: "unique" },
  14001: { name: "crownMedal", color: "green", type: "unique" },
  14002: { name: "blessedIronCoin", color: "green", type: "unique" },
  15000: { name: "tornBraidedCord", color: "blue", type: "unique" },
  15002: { name: "blackClawNecklace", color: "yellow", type: "unique" },
  16001: { name: "smallMakeupBrush", color: "blue", type: "unique" },
  16002: { name: "oldPortrait", color: "blue", type: "unique" },
  16961: { name: "polishedBurningScene", color: "red", type: "relic" },
  16962: { name: "grandBurningScene", color: "red", type: "relic" },
  16971: { name: "polishedBurningScene", color: "red", type: "relic" },
  16972: { name: "grandBurningScene", color: "red", type: "relic" },
  16982: { name: "grandBurningScene", color: "red", type: "relic" },
  17001: { name: "vestigeOfNight", color: "green", type: "unique" },
  17002: { name: "boneLikeStone", color: "green", type: "unique" },
  17061: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  17071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  17081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  17160: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  17162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  17171: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  17181: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  17182: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  17261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  17262: { name: "grandTranquilScene", color: "green", type: "relic" },
  17271: { name: "polishedTranquilScene", color: "green", type: "relic" },
  17272: { name: "grandTranquilScene", color: "green", type: "relic" },
  17281: { name: "polishedTranquilScene", color: "green", type: "relic" },
  17282: { name: "grandTranquilScene", color: "green", type: "relic" },
  17961: { name: "polishedBurningScene", color: "red", type: "relic" },
  17962: { name: "grandBurningScene", color: "red", type: "relic" },
  17971: { name: "polishedBurningScene", color: "red", type: "relic" },
  17972: { name: "grandBurningScene", color: "red", type: "relic" },
  17981: { name: "polishedBurningScene", color: "red", type: "relic" },
  17982: { name: "grandBurningScene", color: "red", type: "relic" },
  18000: { name: "blessedFlowers", color: "green", type: "unique" },
  18002: { name: "goldenSprout", color: "red", type: "unique" },
  18071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  18072: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  18081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  18082: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  18161: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  18162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  18171: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  18172: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  18181: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  18182: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  18261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  18262: { name: "grandTranquilScene", color: "green", type: "relic" },
  18271: { name: "polishedTranquilScene", color: "green", type: "relic" },
  18272: { name: "grandTranquilScene", color: "green", type: "relic" },
  18281: { name: "polishedTranquilScene", color: "green", type: "relic" },
  18282: { name: "grandTranquilScene", color: "green", type: "relic" },
  18962: { name: "grandBurningScene", color: "red", type: "relic" },
  18971: { name: "polishedBurningScene", color: "red", type: "relic" },
  18972: { name: "grandBurningScene", color: "red", type: "relic" },
  18982: { name: "grandBurningScene", color: "red", type: "relic" },
  19062: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  19071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  19072: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  19080: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  19081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  19082: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  19160: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  19161: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  19162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  19171: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  19172: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  19181: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  19182: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  19261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  19272: { name: "grandTranquilScene", color: "green", type: "relic" },
  19281: { name: "polishedTranquilScene", color: "green", type: "relic" },
  19282: { name: "grandTranquilScene", color: "green", type: "relic" },
  19961: { name: "polishedBurningScene", color: "red", type: "relic" },
  19962: { name: "grandBurningScene", color: "red", type: "relic" },
  19972: { name: "grandBurningScene", color: "red", type: "relic" },
  19981: { name: "polishedBurningScene", color: "red", type: "relic" },
  19982: { name: "grandBurningScene", color: "red", type: "relic" },
  20000: { name: "delicateBurningScene", color: "red", type: "relic" },
  20001: { name: "polishedBurningScene", color: "red", type: "relic" },
  20002: { name: "grandBurningScene", color: "red", type: "relic" },
  20003: { name: "delicateBurningScene", color: "red", type: "relic" },
  20004: { name: "polishedBurningScene", color: "red", type: "relic" },
  20005: { name: "grandBurningScene", color: "red", type: "relic" },
  20006: { name: "delicateBurningScene", color: "red", type: "relic" },
  20007: { name: "polishedBurningScene", color: "red", type: "relic" },
  20008: { name: "grandBurningScene", color: "red", type: "relic" },
  20009: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  20010: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  20011: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  20012: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  20013: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  20014: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  20015: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  20016: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  20017: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  20018: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  20019: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  20020: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  20021: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  20022: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  20023: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  20024: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  20025: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  20026: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  20027: { name: "delicateTranquilScene", color: "green", type: "relic" },
  20028: { name: "polishedTranquilScene", color: "green", type: "relic" },
  20029: { name: "grandTranquilScene", color: "green", type: "relic" },
  20030: { name: "delicateTranquilScene", color: "green", type: "relic" },
  20031: { name: "polishedTranquilScene", color: "green", type: "relic" },
  20032: { name: "grandTranquilScene", color: "green", type: "relic" },
  20033: { name: "delicateTranquilScene", color: "green", type: "relic" },
  20034: { name: "polishedTranquilScene", color: "green", type: "relic" },
  20035: { name: "grandTranquilScene", color: "green", type: "relic" },
  20060: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  20061: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  20062: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  20071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  20072: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  20081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  20082: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  20162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  20172: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  20261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  20961: { name: "polishedBurningScene", color: "red", type: "relic" },
  20962: { name: "grandBurningScene", color: "red", type: "relic" },
  20971: { name: "polishedBurningScene", color: "red", type: "relic" },
  20972: { name: "grandBurningScene", color: "red", type: "relic" },
  20981: { name: "polishedBurningScene", color: "red", type: "relic" },
  20982: { name: "grandBurningScene", color: "red", type: "relic" },
  21061: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  21062: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  21072: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  21081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  21082: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  21161: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  21162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  21171: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  21172: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  21180: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  21181: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  21182: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  21261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  21262: { name: "grandTranquilScene", color: "green", type: "relic" },
  21271: { name: "polishedTranquilScene", color: "green", type: "relic" },
  21281: { name: "polishedTranquilScene", color: "green", type: "relic" },
  21282: { name: "grandTranquilScene", color: "green", type: "relic" },
  21961: { name: "polishedBurningScene", color: "red", type: "relic" },
  21962: { name: "grandBurningScene", color: "red", type: "relic" },
  21971: { name: "polishedBurningScene", color: "red", type: "relic" },
  21972: { name: "grandBurningScene", color: "red", type: "relic" },
  21981: { name: "polishedBurningScene", color: "red", type: "relic" },
  21982: { name: "grandBurningScene", color: "red", type: "relic" },
  22062: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  22071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  22072: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  22081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  22082: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  22161: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  22162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  22171: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  22172: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  22180: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  22181: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  22182: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  22262: { name: "grandTranquilScene", color: "green", type: "relic" },
  22271: { name: "polishedTranquilScene", color: "green", type: "relic" },
  22272: { name: "grandTranquilScene", color: "green", type: "relic" },
  22281: { name: "polishedTranquilScene", color: "green", type: "relic" },
  22282: { name: "grandTranquilScene", color: "green", type: "relic" },
  22961: { name: "polishedBurningScene", color: "red", type: "relic" },
  22972: { name: "grandBurningScene", color: "red", type: "relic" },
  22981: { name: "polishedBurningScene", color: "red", type: "relic" },
  23061: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  23062: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  23071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  23072: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  23081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  23082: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  23261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  23262: { name: "grandTranquilScene", color: "green", type: "relic" },
  23271: { name: "polishedTranquilScene", color: "green", type: "relic" },
  23272: { name: "grandTranquilScene", color: "green", type: "relic" },
  23281: { name: "polishedTranquilScene", color: "green", type: "relic" },
  23282: { name: "grandTranquilScene", color: "green", type: "relic" },
  23961: { name: "polishedBurningScene", color: "red", type: "relic" },
  23962: { name: "grandBurningScene", color: "red", type: "relic" },
  23971: { name: "polishedBurningScene", color: "red", type: "relic" },
  23972: { name: "grandBurningScene", color: "red", type: "relic" },
  23981: { name: "polishedBurningScene", color: "red", type: "relic" },
  23982: { name: "grandBurningScene", color: "red", type: "relic" },
  24061: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  24062: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  24071: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  24081: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  24162: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  24172: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  24181: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  24182: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  24261: { name: "polishedTranquilScene", color: "green", type: "relic" },
  24262: { name: "grandTranquilScene", color: "green", type: "relic" },
  24272: { name: "grandTranquilScene", color: "green", type: "relic" },
  24282: { name: "grandTranquilScene", color: "green", type: "relic" },
  30000: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  30001: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  30002: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  30003: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  30004: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  30005: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  30006: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  30007: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  30008: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  30009: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  30010: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  30011: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  30012: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  30013: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  30014: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  30015: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  30016: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  30017: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  30018: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  30019: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  30020: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  30021: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  30022: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  30023: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  30024: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  30025: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  30026: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  30027: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  30028: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  30029: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  30030: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  30031: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  30032: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  30033: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  30034: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  30035: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  1000000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1000001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1000002: { name: "grandBurningScene", color: "red", type: "relic" },
  1000010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1000011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1000012: { name: "grandBurningScene", color: "red", type: "relic" },
  1000020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1000021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1000022: { name: "grandBurningScene", color: "red", type: "relic" },
  1000100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1000101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1000102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1000110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1000111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1000112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1000120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1000121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1000122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1000200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1000201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1000202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1000210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1000211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1000212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1000220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1000221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1000222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1000300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1000301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1000302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1000310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1000311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1000312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1000320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1000321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1000322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1001000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1001001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1001002: { name: "grandBurningScene", color: "red", type: "relic" },
  1001010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1001011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1001012: { name: "grandBurningScene", color: "red", type: "relic" },
  1001020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1001021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1001022: { name: "grandBurningScene", color: "red", type: "relic" },
  1001100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1001101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1001102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1001110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1001111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1001112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1001120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1001121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1001122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1001200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1001201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1001202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1001210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1001211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1001212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1001220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1001221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1001222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1001300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1001301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1001302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1001310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1001311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1001312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1001320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1001321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1001322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1002000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1002001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1002002: { name: "grandBurningScene", color: "red", type: "relic" },
  1002010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1002011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1002012: { name: "grandBurningScene", color: "red", type: "relic" },
  1002020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1002021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1002022: { name: "grandBurningScene", color: "red", type: "relic" },
  1002100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1002101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1002102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1002110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1002111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1002112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1002120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1002121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1002122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1002200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1002201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1002202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1002210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1002211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1002212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1002220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1002221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1002222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1002300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1002301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1002302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1002310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1002311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1002312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1002320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1002321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1002322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1003000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1003001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1003002: { name: "grandBurningScene", color: "red", type: "relic" },
  1003010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1003011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1003012: { name: "grandBurningScene", color: "red", type: "relic" },
  1003020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1003021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1003022: { name: "grandBurningScene", color: "red", type: "relic" },
  1003100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1003101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1003102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1003110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1003111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1003112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1003120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1003121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1003122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1003200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1003201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1003202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1003210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1003211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1003212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1003220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1003221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1003222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1003300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1003301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1003302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1003310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1003311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1003312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1003320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1003321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1003322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1004000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1004001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1004002: { name: "grandBurningScene", color: "red", type: "relic" },
  1004010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1004011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1004012: { name: "grandBurningScene", color: "red", type: "relic" },
  1004020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1004021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1004022: { name: "grandBurningScene", color: "red", type: "relic" },
  1004100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1004101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1004102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1004110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1004111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1004112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1004120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1004121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1004122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1004200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1004201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1004202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1004210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1004211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1004212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1004220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1004221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1004222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1004300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1004301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1004302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1004310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1004311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1004312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1004320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1004321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1004322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1005000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1005001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1005002: { name: "grandBurningScene", color: "red", type: "relic" },
  1005010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1005011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1005012: { name: "grandBurningScene", color: "red", type: "relic" },
  1005020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1005021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1005022: { name: "grandBurningScene", color: "red", type: "relic" },
  1005100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1005101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1005102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1005110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1005111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1005112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1005120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1005121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1005122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1005200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1005201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1005202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1005210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1005211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1005212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1005220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1005221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1005222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1005300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1005301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1005302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1005310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1005311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1005312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1005320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1005321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1005322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1006000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1006001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1006002: { name: "grandBurningScene", color: "red", type: "relic" },
  1006010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1006011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1006012: { name: "grandBurningScene", color: "red", type: "relic" },
  1006020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1006021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1006022: { name: "grandBurningScene", color: "red", type: "relic" },
  1006100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1006101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1006102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1006110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1006111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1006112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1006120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1006121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1006122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1006200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1006201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1006202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1006210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1006211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1006212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1006220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1006221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1006222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1006300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1006301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1006302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1006310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1006311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1006312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1006320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1006321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1006322: { name: "grandTranquilScene", color: "green", type: "relic" },
  1007000: { name: "delicateBurningScene", color: "red", type: "relic" },
  1007001: { name: "polishedBurningScene", color: "red", type: "relic" },
  1007002: { name: "grandBurningScene", color: "red", type: "relic" },
  1007010: { name: "delicateBurningScene", color: "red", type: "relic" },
  1007011: { name: "polishedBurningScene", color: "red", type: "relic" },
  1007012: { name: "grandBurningScene", color: "red", type: "relic" },
  1007020: { name: "delicateBurningScene", color: "red", type: "relic" },
  1007021: { name: "polishedBurningScene", color: "red", type: "relic" },
  1007022: { name: "grandBurningScene", color: "red", type: "relic" },
  1007100: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1007101: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1007102: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1007110: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1007111: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1007112: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1007120: { name: "delicateDrizzlyScene", color: "blue", type: "relic" },
  1007121: { name: "polishedDrizzlyScene", color: "blue", type: "relic" },
  1007122: { name: "grandDrizzlyScene", color: "blue", type: "relic" },
  1007200: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1007201: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1007202: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1007210: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1007211: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1007212: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1007220: { name: "delicateLuminousScene", color: "yellow", type: "relic" },
  1007221: { name: "polishedLuminousScene", color: "yellow", type: "relic" },
  1007222: { name: "grandLuminousScene", color: "yellow", type: "relic" },
  1007300: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1007301: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1007302: { name: "grandTranquilScene", color: "green", type: "relic" },
  1007310: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1007311: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1007312: { name: "grandTranquilScene", color: "green", type: "relic" },
  1007320: { name: "delicateTranquilScene", color: "green", type: "relic" },
  1007321: { name: "polishedTranquilScene", color: "green", type: "relic" },
  1007322: { name: "grandTranquilScene", color: "green", type: "relic" },
  2000000: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  2000001: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2000002: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2000010: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  2000011: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2000012: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2000020: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  2000021: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2000022: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2000100: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  2000101: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2000102: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2000110: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  2000111: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2000112: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2000120: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  2000121: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2000122: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2000200: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  2000201: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2000202: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2000210: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  2000211: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2000212: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2000220: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  2000221: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2000222: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2000300: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  2000301: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2000302: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2000310: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  2000311: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2000312: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2000320: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  2000321: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2000322: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2001001: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2001002: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2001011: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2001012: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2001021: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2001022: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2001101: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2001102: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2001111: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2001112: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2001121: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2001122: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2001201: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2001202: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2001211: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2001212: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2001221: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2001222: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2001301: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2001302: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2001311: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2001312: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2001321: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2001322: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2002002: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2002012: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2002022: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2002102: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2002112: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2002122: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2002202: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2002212: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2002222: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2002302: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2002312: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2002322: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2003000: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  2003001: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2003002: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2003010: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  2003011: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2003012: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2003020: { name: "deepDelicateBurningScene", color: "red", type: "deepRelic" },
  2003021: { name: "deepPolishedBurningScene", color: "red", type: "deepRelic" },
  2003022: { name: "deepGrandBurningScene", color: "red", type: "deepRelic" },
  2003100: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  2003101: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2003102: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2003110: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  2003111: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2003112: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2003120: { name: "deepDelicateDrizzlyScene", color: "blue", type: "deepRelic" },
  2003121: { name: "deepPolishedDrizzlyScene", color: "blue", type: "deepRelic" },
  2003122: { name: "deepGrandDrizzlyScene", color: "blue", type: "deepRelic" },
  2003200: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  2003201: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2003202: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2003210: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  2003211: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2003212: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2003220: { name: "deepDelicateLuminousScene", color: "yellow", type: "deepRelic" },
  2003221: { name: "deepPolishedLuminousScene", color: "yellow", type: "deepRelic" },
  2003222: { name: "deepGrandLuminousScene", color: "yellow", type: "deepRelic" },
  2003300: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  2003301: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2003302: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2003310: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  2003311: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2003312: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
  2003320: { name: "deepDelicateTranquilScene", color: "green", type: "deepRelic" },
  2003321: { name: "deepPolishedTranquilScene", color: "green", type: "deepRelic" },
  2003322: { name: "deepGrandTranquilScene", color: "green", type: "deepRelic" },
};

export const Effects = {
  10000: { name: "fpRestorationUponSuccessiveAttacks" },
  10001: { name: "takingAttacksImprovesAttackPower" },
  10002: { name: "switchingWeaponsBoostsAttackPower" },
  11000: { name: "wylderPlus1AdditionalCharacterSkillUse", character: "wylder" },
  11002: { name: "wylderArtGaugeGreatlyFilledWhenAbilityActivated", character: "wylder" },
  12002: { name: "guardianSlowlyRestoresNearbyAlliesHP", character: "guardian" },
  16002: { name: "revenantExpendOwnHPToFullyHealNearbyAllies", character: "revenant" },
  17002: { name: "recluseSufferBloodLossAndIncreaseAttackPower", character: "recluse" },
  100000: { name: "takingAttacksImprovesAttackPower" },
  6000800: { name: "characterSkillCooldownReductionPlus4" },
  6000801: { name: "characterSkillCooldownReductionPlus5" },
  6000900: { name: "ultimateArtGaugePlus4" },
  6000901: { name: "ultimateArtGaugePlus5" },
  6001000: { name: "poisePlus4" },
  6001001: { name: "poisePlus5" },
  6001400: { name: "physicalAttackUpPlus3" },
  6001401: { name: "physicalAttackUpPlus4" },
  6001500: { name: "magicAttackPowerUpPlus3" },
  6001501: { name: "magicAttackPowerUpPlus4" },
  6001600: { name: "fireAttackPowerUpPlus3" },
  6001601: { name: "fireAttackPowerUpPlus4" },
  6001700: { name: "lightningAttackPowerUpPlus3" },
  6001701: { name: "lightningAttackPowerUpPlus4" },
  6001800: { name: "holyAttackPowerUpPlus3" },
  6001801: { name: "holyAttackPowerUpPlus4" },
  6002600: { name: "improvedMagicDamageNegationPlus1" },
  6002601: { name: "improvedMagicDamageNegationPlus2" },
  6002700: { name: "improvedFireDamageNegationPlus1" },
  6002701: { name: "improvedFireDamageNegationPlus2" },
  6002800: { name: "improvedLightningDamageNegationPlus1" },
  6002801: { name: "improvedLightningDamageNegationPlus2" },
  6002900: { name: "improvedHolyDamageNegationPlus1" },
  6002901: { name: "improvedHolyDamageNegationPlus2" },
  6003000: { name: "improvedPoisonResistancePlus1" },
  6003001: { name: "improvedPoisonResistancePlus2" },
  6003100: { name: "improvedBloodLossResistancePlus1" },
  6003101: { name: "improvedBloodLossResistancePlus2" },
  6003200: { name: "improvedSleepResistancePlus1" },
  6003201: { name: "improvedSleepResistancePlus2" },
  6003300: { name: "improvedDeathBlightResistancePlus1" },
  6003301: { name: "improvedDeathBlightResistancePlus2" },
  6003400: { name: "improvedRotResistancePlus1" },
  6003401: { name: "improvedRotResistancePlus2" },
  6003500: { name: "improvedFrostResistancePlus1" },
  6003501: { name: "improvedFrostResistancePlus2" },
  6003600: { name: "improvedMadnessResistancePlus1" },
  6003601: { name: "improvedMadnessResistancePlus2" },
  6005600: { name: "partialHPRestorationUponPostDamageAttacksPlus1" },
  6005601: { name: "partialHPRestorationUponPostDamageAttacksPlus2" },
  6030200: { name: "hpRestoredWhenUsingMedicinalBolusesEtcPlus1" },
  6030201: { name: "hpRestoredWhenUsingMedicinalBolusesEtcPlus2" },
  6030600: { name: "artGaugeChargedFromSuccessfulGuardingPlus1" },
  6030601: { name: "artGaugeChargedFromSuccessfulGuardingPlus2" },
  6030800: { name: "artGaugeFillsModeratelyUponCriticalHitPlus1" },
  6030801: { name: "artGaugeFillsModeratelyUponCriticalHitPlus2" },
  6030900: { name: "physicalAttackPowerIncreasesAfterUsingGreaseItemsPlus1" },
  6030901: { name: "physicalAttackPowerIncreasesAfterUsingGreaseItemsPlus2" },
  6035100: { name: "criticalHitBoostsStaminaRecoverySpeedPlus1" },
  6040100: { name: "improvedGuardCountersPlus1" },
  6040101: { name: "improvedGuardCountersPlus2" },
  6040300: { name: "improvedThrowingPotDamagePlus1" },
  6040301: { name: "improvedThrowingPotDamagePlus2" },
  6040400: { name: "improvedThrowingKnifeDamagePlus1" },
  6040401: { name: "improvedThrowingKnifeDamagePlus2" },
  6040500: { name: "improvedGlintstoneAndGravityStoneDamagePlus1" },
  6040501: { name: "improvedGlintstoneAndGravityStoneDamagePlus2" },
  6043000: { name: "improvedRoarAndBreathAttacksPlus1" },
  6043001: { name: "improvedRoarAndBreathAttacksPlus2" },
  6043100: { name: "improvedPerfumingArtsPlus1" },
  6043101: { name: "improvedPerfumingArtsPlus2" },
  6060300: { name: "maxHPIncreasedForEachGreatEnemyDefeatedAtAGreatChurch" },
  6060400: { name: "runesAndItemDiscoveryIncreasedForEachGreatEnemyDefeatedAtAFort" },
  6060500: { name: "arcaneIncreasedForEachGreatEnemyDefeatedAtARuin" },
  6060600: { name: "maxStaminaIncreasedForEachGreatEnemyDefeatedAtAGreatEncampment" },
  6090000: { name: "defeatingEnemiesFillsMoreOfTheArtGaugePlus1" },
  6090001: { name: "defeatingEnemiesFillsMoreOfTheArtGaugePlus2" },
  6160000: { name: "hpRestorationUponThrustingCounterattackPlus1" },
  6160001: { name: "hpRestorationUponThrustingCounterattackPlus2" },
  6260000: { name: "attackPowerUpWhenFacingPoisonAfflictedEnemyPlus1" },
  6260001: { name: "attackPowerUpWhenFacingPoisonAfflictedEnemyPlus2" },
  6260300: { name: "attackPowerUpWhenFacingScarletRotAfflictedEnemyPlus1" },
  6260301: { name: "attackPowerUpWhenFacingScarletRotAfflictedEnemyPlus2" },
  6260400: { name: "attackPowerUpWhenFacingFrostbiteAfflictedEnemyPlus1" },
  6260401: { name: "attackPowerUpWhenFacingFrostbiteAfflictedEnemyPlus2" },
  6500000: { name: "wylderCharacterSkillInflictsBloodLoss", character: "wylder" },
  6500100: { name: "guardianCharacterSkillBoostsDamageNegationOfNearbyAllies", character: "guardian" },
  6500200: { name: "ironeyeCharacterSkillInflictsHeavyPoisonDamageOnPoisonedEnemies", character: "ironeye" },
  6500300: { name: "duchessUseCharacterSkillForBriefInvulnerability", character: "duchess" },
  6500400: { name: "raiderHitWithCharacterSkillToReduceEnemyAttackPower", character: "raider" },
  6500500: { name: "revenantIncreasedMaxFPUponAbilityActivation", character: "revenant" },
  6500600: { name: "recluseCollectAffinityResiduesToNegateAffinity", character: "recluse" },
  6500700: { name: "executorSlowlyRestoreHPUponAbilityActivation", character: "executor" },
  6600000: { name: "sleepInVicinityImprovesAttackPower" },
  6600001: { name: "sleepInVicinityImprovesAttackPowerPlus1" },
  6600002: { name: "sleepInVicinityImprovesAttackPowerPlus2" },
  6600100: { name: "madnessInVicinityImprovesAttackPower" },
  6600101: { name: "madnessInVicinityImprovesAttackPowerPlus1" },
  6600102: { name: "madnessInVicinityImprovesAttackPowerPlus2" },
  6610400: { name: "increasedMaximumHP" },
  6610500: { name: "increasedMaximumFP" },
  6610600: { name: "increasedMaximumStamina" },
  6610700: { name: "reducedFPConsumption" },
  6610701: { name: "reducedFPConsumptionPlus1" },
  6610702: { name: "reducedFPConsumptionPlus2" },
  6610800: { name: "improvedAffinityAttackPower" },
  6610801: { name: "improvedAffinityAttackPowerPlus1" },
  6610802: { name: "improvedAffinityAttackPowerPlus2" },
  6611001: { name: "improvedPhysicalDamageNegationPlus1" },
  6611002: { name: "improvedPhysicalDamageNegationPlus2" },
  6611100: { name: "improvedAffinityDamageNegation" },
  6611101: { name: "improvedAffinityDamageNegationPlus1" },
  6611102: { name: "improvedAffinityDamageNegationPlus2" },
  6611200: { name: "improvedSorceries" },
  6611201: { name: "improvedSorceriesPlus1" },
  6611202: { name: "improvedSorceriesPlus2" },
  6611300: { name: "improvedIncantations" },
  6611301: { name: "improvedIncantationsPlus1" },
  6611302: { name: "improvedIncantationsPlus2" },
  6611400: { name: "improvedFlaskHPRestoration" },
  6621000: { name: "crimsonspillCrystalTearInPossessionAtStartOfExpedition" },
  6621100: { name: "crimsonCrystalTearInPossessionAtStartOfExpedition" },
  6621200: { name: "ceruleanCrystalTearInPossessionAtStartOfExpedition" },
  6621300: { name: "speckledHardtearInPossessionAtStartOfExpedition" },
  6621400: { name: "crimsonBubbletearInPossessionAtStartOfExpedition" },
  6621500: { name: "opalineBubbletearInPossessionAtStartOfExpedition" },
  6621600: { name: "crimsonburstCrystalTearInPossessionAtStartOfExpedition" },
  6621700: { name: "greenburstCrystalTearInPossessionAtStartOfExpedition" },
  6621800: { name: "opalineHardtearInPossessionAtStartOfExpedition" },
  6621900: { name: "thornyCrackedTearInPossessionAtStartOfExpedition" },
  6622000: { name: "spikedCrackedTearInPossessionAtStartOfExpedition" },
  6622100: { name: "windyCrystalTearInPossessionAtStartOfExpedition" },
  6622200: { name: "rupturedCrystalTearInPossessionAtStartOfExpedition" },
  6622300: { name: "leadenHardtearInPossessionAtStartOfExpedition" },
  6622400: { name: "twiggyCrackedTearInPossessionAtStartOfExpedition" },
  6622500: { name: "crimsonwhorlBubbletearInPossessionAtStartOfExpedition" },
  6622600: { name: "ceruleanHiddenTearInPossessionAtStartOfExpedition" },
  6622700: { name: "stonebarbCrackedTearInPossessionAtStartOfExpedition" },
  6622800: { name: "flameShroudingCrackedTearInPossessionAtStartOfExpedition" },
  6622900: { name: "magicShroudingCrackedTearInPossessionAtStartOfExpedition" },
  6623000: { name: "lightningShroudingCrackedTearInPossessionAtStartOfExpedition" },
  6623100: { name: "holyShroudingCrackedTearInPossessionAtStartOfExpedition" },
  6624000: { name: "upliftingAromaticInPossessionAtStartOfExpedition" },
  6624100: { name: "sparkAromaticInPossessionAtStartOfExpedition" },
  6624200: { name: "ironjarAromaticInPossessionAtStartOfExpedition" },
  6624300: { name: "bloodboilAromaticInPossessionAtStartOfExpedition" },
  6624400: { name: "poisonSpraymistInPossessionAtStartOfExpedition" },
  6624500: { name: "acidSpraymistInPossessionAtStartOfExpedition" },
  6630000: { name: "dormantPowerHelpsDiscoverDaggers" },
  6630100: { name: "dormantPowerHelpsDiscoverStraightSwords" },
  6630200: { name: "dormantPowerHelpsDiscoverGreatswords" },
  6630300: { name: "dormantPowerHelpsDiscoverColossalSwords" },
  6630400: { name: "dormantPowerHelpsDiscoverCurvedSwords" },
  6630500: { name: "dormantPowerHelpsDiscoverCurvedGreatswords" },
  6630600: { name: "dormantPowerHelpsDiscoverKatana" },
  6630700: { name: "dormantPowerHelpsDiscoverTwinblades" },
  6630800: { name: "dormantPowerHelpsDiscoverThrustingSwords" },
  6630900: { name: "dormantPowerHelpsDiscoverHeavyThrustingSwords" },
  6631000: { name: "dormantPowerHelpsDiscoverAxes" },
  6631100: { name: "dormantPowerHelpsDiscoverGreataxes" },
  6631200: { name: "dormantPowerHelpsDiscoverHammers" },
  6631300: { name: "dormantPowerHelpsDiscoverGreatHammers" },
  6631400: { name: "dormantPowerHelpsDiscoverFlails" },
  6631500: { name: "dormantPowerHelpsDiscoverSpears" },
  6631600: { name: "dormantPowerHelpsDiscoverGreatSpears" },
  6631700: { name: "dormantPowerHelpsDiscoverHalberds" },
  6631800: { name: "dormantPowerHelpsDiscoverReapers" },
  6631900: { name: "dormantPowerHelpsDiscoverFists" },
  6632000: { name: "dormantPowerHelpsDiscoverClaws" },
  6632100: { name: "dormantPowerHelpsDiscoverWhips" },
  6632200: { name: "dormantPowerHelpsDiscoverColossalWeapons" },
  6632300: { name: "dormantPowerHelpsDiscoverBows" },
  6632400: { name: "dormantPowerHelpsDiscoverGreatbows" },
  6632500: { name: "dormantPowerHelpsDiscoverCrossbows" },
  6632600: { name: "dormantPowerHelpsDiscoverBallistas" },
  6632700: { name: "dormantPowerHelpsDiscoverSmallShields" },
  6632800: { name: "dormantPowerHelpsDiscoverMediumShields" },
  6632900: { name: "dormantPowerHelpsDiscoverGreatshields" },
  6633000: { name: "dormantPowerHelpsDiscoverStaves" },
  6633100: { name: "dormantPowerHelpsDiscoverSacredSeals" },
  6633200: { name: "dormantPowerHelpsDiscoverTorches" },
  6640000: { name: "wylderImprovedMindReducedVigor", character: "wylder" },
  6640100: { name: "wylderImprovedIntelligenceAndFaithReducedStrengthAndDexterity", character: "wylder" },
  6641000: { name: "guardianImprovedStrengthAndDexterityReducedVigor", character: "guardian" },
  6641100: { name: "guardianImprovedMindAndFaithReducedVigor", character: "guardian" },
  6642000: { name: "ironeyeImprovedArcaneReducedDexterity", character: "ironeye" },
  6642100: { name: "ironeyeImprovedVigorAndStrengthReducedDexterity", character: "ironeye" },
  6643000: { name: "duchessImprovedVigorAndStrengthReducedMind", character: "duchess" },
  6643100: { name: "duchessImprovedMindAndFaithReducedIntelligence", character: "duchess" },
  6644000: { name: "raiderImprovedMindAndIntelligenceReducedVigorAndEndurance", character: "raider" },
  6644100: { name: "raiderImprovedArcaneReducedVigor", character: "raider" },
  6645000: { name: "revenantImprovedVigorAndEnduranceReducedMind", character: "revenant" },
  6645100: { name: "revenantImprovedStrengthReducedFaith", character: "revenant" },
  6646000: { name: "recluseImprovedVigorEnduranceAndDexterityReducedIntelligenceAndFaith", character: "recluse" },
  6646100: { name: "recluseImprovedIntelligenceAndFaithReducedMind", character: "recluse" },
  6647000: { name: "executorImprovedVigorAndEnduranceReducedArcane", character: "executor" },
  6647100: { name: "executorImprovedDexterityAndArcaneReducedVigor", character: "executor" },
  6800000: { name: "reducedVigor", type: "curse" },
  6800200: { name: "reducedEndurance", type: "curse" },
  6810100: { name: "impairedDamageNegation" },
  6820000: { name: "takingDamageCausesPoisonBuildup", type: "curse" },
  6820100: { name: "takingDamageCausesRotBuildup", type: "curse" },
  6820200: { name: "takingDamageCausesFrostBuildup", type: "curse" },
  6820300: { name: "takingDamageCausesBloodLossBuildup", type: "curse" },
  6820400: { name: "takingDamageCausesMadnessBuildup", type: "curse" },
  6820500: { name: "takingDamageCausesSleepBuildup", type: "curse" },
  6820600: { name: "takingDamageCausesDeathBuildup", type: "curse" },
  6830000: { name: "reducedStrengthAndIntelligence", type: "curse" },
  6830100: { name: "reducedDexterityAndFaith", type: "curse" },
  6830200: { name: "reducedIntelligenceAndDexterity", type: "curse" },
  6830300: { name: "reducedFaithAndStrength", type: "curse" },
  6830400: { name: "reducedVigorAndArcane", type: "curse" },
  6840000: { name: "reducedRuneAcquisition", type: "curse" },
  6840100: { name: "reducedFlaskHPRestoration", type: "curse" },
  6840200: { name: "ultimateArtChargingImpaired", type: "curse" },
  6850000: { name: "impairedPhysicalDamageNegation" },
  6850100: { name: "impairedAffinityDamageNegation", type: "curse" },
  6850200: { name: "allResistancesDown", type: "curse" },
  6850300: { name: "reducedFlaskHPRestoration", type: "curse" },
  6850400: { name: "surgeSprintingDrainsMoreStamina", type: "curse" },
  6850500: { name: "continuousHPLoss", type: "curse" },
  6850600: { name: "increasedDrainOnStaminaForEvasion", type: "curse" },
  6850700: { name: "moreDamageTakenAfterEvasion", type: "curse" },
  6850800: { name: "repeatedEvasionsLowerDamageNegation", type: "curse" },
  6850900: { name: "reducedDamageNegationForFlaskUsages", type: "curse" },
  6851000: { name: "sleepBuildupForFlaskUsages", type: "curse" },
  6851100: { name: "madnessBuildupForFlaskUsages", type: "curse" },
  6851200: { name: "lowerAttackWhenBelowMaxHP", type: "curse" },
  6851300: { name: "poisonBuildupWhenBelowMaxHP", type: "curse" },
  6851400: { name: "rotBuildupWhenBelowMaxHP", type: "curse" },
  6851500: { name: "maxHPReducesAttackPower", type: "curse" },
  6851600: { name: "nearDeathSpillsFlask", type: "curse" },
  6851700: { name: "nearDeathReducesMaxHP", type: "curse" },
  7000000: { name: "vigorPlus1" },
  7000001: { name: "vigorPlus2" },
  7000002: { name: "vigorPlus3" },
  7000090: { name: "increasedMaximumHP" },
  7000100: { name: "mindPlus1" },
  7000101: { name: "mindPlus2" },
  7000102: { name: "mindPlus3" },
  7000190: { name: "increasedMaximumFP" },
  7000200: { name: "endurancePlus1" },
  7000201: { name: "endurancePlus2" },
  7000202: { name: "endurancePlus3" },
  7000290: { name: "increasedMaximumStamina" },
  7000300: { name: "strengthPlus1" },
  7000301: { name: "strengthPlus2" },
  7000302: { name: "strengthPlus3" },
  7000400: { name: "dexterityPlus1" },
  7000401: { name: "dexterityPlus2" },
  7000402: { name: "dexterityPlus3" },
  7000500: { name: "intelligencePlus1" },
  7000501: { name: "intelligencePlus2" },
  7000502: { name: "intelligencePlus3" },
  7000600: { name: "faithPlus1" },
  7000601: { name: "faithPlus2" },
  7000602: { name: "faithPlus3" },
  7000700: { name: "arcanePlus1" },
  7000701: { name: "arcanePlus2" },
  7000702: { name: "arcanePlus3" },
  7000800: { name: "characterSkillCooldownReductionPlus1" },
  7000801: { name: "characterSkillCooldownReductionPlus2" },
  7000802: { name: "characterSkillCooldownReductionPlus3" },
  7000900: { name: "ultimateArtGaugePlus1" },
  7000901: { name: "ultimateArtGaugePlus2" },
  7000902: { name: "ultimateArtGaugePlus3" },
  7001000: { name: "poisePlus1" },
  7001001: { name: "poisePlus2" },
  7001002: { name: "poisePlus3" },
  7001100: { name: "continuousHPRecovery" },
  7001400: { name: "physicalAttackUp" },
  7001401: { name: "physicalAttackUpPlus1" },
  7001402: { name: "physicalAttackUpPlus2" },
  7001403: { name: "physicalAttackUpPlus3" },
  7001500: { name: "magicAttackPowerUp" },
  7001501: { name: "magicAttackPowerUpPlus1" },
  7001502: { name: "magicAttackPowerUpPlus2" },
  7001600: { name: "fireAttackPowerUp" },
  7001601: { name: "fireAttackPowerUpPlus1" },
  7001602: { name: "fireAttackPowerUpPlus2" },
  7001700: { name: "lightningAttackPowerUp" },
  7001701: { name: "lightningAttackPowerUpPlus1" },
  7001702: { name: "lightningAttackPowerUpPlus2" },
  7001800: { name: "holyAttackPowerUp" },
  7001801: { name: "holyAttackPowerUpPlus1" },
  7001802: { name: "holyAttackPowerUpPlus2" },
  7002600: { name: "magicDamageNegationUp" },
  7002700: { name: "fireDamageNegationUp" },
  7002800: { name: "lightningDamageNegationUp" },
  7002900: { name: "holyDamageNegationUp" },
  7003000: { name: "improvedPoisonResistance" },
  7003100: { name: "improvedBloodLossResistance" },
  7003200: { name: "improvedSleepResistance" },
  7003300: { name: "improvedDeathBlightResistance" },
  7003400: { name: "improvedRotResistance" },
  7003500: { name: "improvedFrostResistance" },
  7003600: { name: "improvedMadnessResistance" },
  7005600: { name: "partialHpRestorationUponPostDamageAttacks" },
  7006000: { name: "improvedStanceBreakingWhenTwoHanding" },
  7006001: { name: "improvedStanceBreakingWhenTwoHanding" },
  7006100: { name: "improvedStanceBreakingWhenWieldingTwoArmaments" },
  7006101: { name: "improvedStanceBreakingWhenWieldingTwoArmaments" },
  7006200: { name: "improvedPhysicalDamageNegation" },
  7010000: { name: "guardianImprovedCharacterSkillRange", character: "guardian" },
  7010200: { name: "flaskAlsoHealsAllies" },
  7010500: { name: "wylderArtActivationSpreadsFireInArea", character: "wylder" },
  7010700: { name: "duchessDaggerChainAttackReprises", character: "duchess" },
  7010800: { name: "raiderCharacterSkillDamageUp", character: "raider" },
  7010900: { name: "revenantExpendOwnHPToFullyHealNearbyAllies", character: "revenant" },
  7011000: { name: "guardianIncreasedDurationForCharacterSkill", character: "guardian" },
  7011100: { name: "guardianDamageNegationForAlliesImproved", character: "guardian" },
  7011200: { name: "revenantTriggerGhostflameExplosionDuringUltimateArtActivation", character: "revenant" },
  7011400: { name: "guardianRestoresAlliesHPWhenCharacterSkillUsed", character: "guardian" },
  7011500: { name: "wylderCharacterSkillInflictsBloodLoss", character: "wylder" },
  7011600: { name: "guardianCreatesWhirlwindWhenChargingHalberd", character: "guardian" },
  7011700: { name: "executorRoaringRestoresHPWhileArtActive", character: "executor" },
  7011900: { name: "guardianCharacterSkillInflictsHolyDamage", character: "guardian" },
  7012000: { name: "guardianSlowlyRestoresNearbyAlliesHP", character: "guardian" },
  7012200: { name: "slowlyRestoreHpForSelfAndNearbyAlliesWhenHpIsLow" },
  7012300: { name: "improvedDamageNegationAtLowHP" },
  7012400: { name: "strongAttackCreatesWideWaveOfHeat" },
  7012500: { name: "jumpingConjuresMagicProjectiles" },
  7012600: { name: "attackBoostFromNearbyAllies" },
  7012700: { name: "guardCountersCastLightPillar" },
  7020000: { name: "wylderStandardAttacksEnhancedWithFieryFollowUpsWhenUsingCharacterSkill", character: "wylder" },
  7030000: { name: "improvedPoiseNearTotemStela", character: "raider" },
  7030200: { name: "hpRestoredWhenUsingMedicinalBolusesEtc" },
  7030500: { name: "wylderImpairedDamageNegationImprovedAttackPowerStaminaAfterArtActivation", character: "wylder" },
  7030600: { name: "artGaugeChargedFromSuccessfulGuarding" },
  7030700: { name: "drawEnemyAttentionWhileGuarding" },
  7030800: { name: "artGaugeFillsModeratelyUponCriticalHit" },
  7030900: { name: "physicalAttackPowerIncreasesAfterUsingGreaseItems" },
  7031200: { name: "revenantStrengthensFamilyAndAlliesWhenUltimateArtActivated", character: "revenant" },
  7031300: { name: "raiderDamageTakenWhileUsingCharacterSkillImprovesAttack", character: "raider" },
  7031400: { name: "wylderReducedCooldownTimeForCharacterSkill", character: "wylder" },
  7031600: { name: "performingConsecutiveSuccessfulGuardsImprovesGuardAbilityAndDeflectsBigAttacks" },
  7031700: { name: "shockwaveProducedFromSuccessfulGuarding" },
  7031800: { name: "duchessBecomeStealthyAfterCritFromBehind", character: "duchess" },
  7031900: { name: "criticalHitsEarnRunes" },
  7032200: { name: "takingAttacksImprovesAttackPower" },
  7032300: { name: "wylderImprovedAttackPowerWhenCharacterSkillActivated", character: "wylder" },
  7032400: { name: "wylderArtGaugeGreatlyFilledWhenAbilityActivated", character: "wylder" },
  7032700: { name: "duchessDefeatingEnemiesWhileArtActiveUpsAttack", character: "duchess" },
  7032800: { name: "recluseCollectingAffinityResidueActivatesTerraMagica", character: "recluse" },
  7032900: { name: "recluseSufferBloodLossAndIncreaseAttackPower", character: "recluse" },
  7033000: { name: "wylderImprovedAttackPowerWhenAbilityActivated", character: "wylder" },
  7033200: { name: "wylderPlus1AdditionalCharacterSkillUse", character: "wylder" },
  7033300: { name: "guardianBecomeTargetOfEnemyAggression", character: "guardian" },
  7033400: { name: "guardianSuccessfulGuardsSendOutShockwaves", character: "guardian" },
  7033600: { name: "duchessDurationOfUltimateArtExtended", character: "duchess" },
  7033700: { name: "colossalArmamentsCoatedInRockWhenPerformingChargedAttacks" },
  7033800: { name: "raiderPermanentlyIncreaseAttackPower", character: "raider" },
  7033900: { name: "recluseExtendsDurationOfBloodSigils", character: "recluse" },
  7034000: { name: "recluseCollecting4AffinityResiduesImprovesAffinityAttackPower", character: "recluse" },
  7034100: { name: "recluseActivatingUltimateArtRaisesMaxHP", character: "recluse" },
  7034200: { name: "executorAttackPowerUpWhileUltimateArtActive", character: "executor" },
  7034300: { name: "executorImprovesEffectButLowersResistance", character: "executor" },
  7034400: { name: "executorCharacterSkillBoostsAttackButDrainsHP", character: "executor" },
  7034500: { name: "executorUnlockingCursedSwordRestoresHP", character: "executor" },
  7034600: { name: "ironeyeArtChargeActivationAddsPoisonEffect", character: "ironeye" },
  7034700: { name: "ironeyeBoostsThrustingCounterattacksAfterArt", character: "ironeye" },
  7034800: { name: "fireCriticalHitGrantsMaxStaminaBoost" },
  7034900: { name: "criticalHitHPRestoration" },
  7035000: { name: "criticalHitAddsLightningEffect" },
  7035100: { name: "criticalHitBoostsStaminaRecoverySpeed" },
  7035200: { name: "consecutiveGuardsHardenSkin" },
  7035300: { name: "criticalHitCreatesSleepMist" },
  7035400: { name: "gestureCrossedLegsBuildsUpMadness" },
  7035410: { name: "gestureCrossedLegsBuildsUpMadness" },
  7035500: { name: "madnessContinuallyRecoversFP" },
  7035510: { name: "madnessContinuallyRecoversFP" },
  7035600: { name: "surgeSprintLandingsSplitEarth" },
  7035700: { name: "switchingWeaponsAddsAnAffinityAttack" },
  7035800: { name: "boostsAttackPowerOfAddedAffinityAttacks" },
  7035900: { name: "switchingWeaponsBoostsAttackPower" },
  7036000: { name: "fpRestorationUponSuccessiveAttacks" },
  7036100: { name: "hpRecoveryFromSuccessfulGuarding" },
  7040000: { name: "improvedInitialStandardAttack" },
  7040100: { name: "improvedGuardCounters" },
  7040200: { name: "improvedCriticalHits" },
  7040201: { name: "improvedCriticalHitsPlus1" },
  7040290: { name: "improvedCriticalHitsPlus1" },
  7040300: { name: "improvedThrowingPotDamage" },
  7040400: { name: "improvedThrowingKnifeDamage" },
  7040500: { name: "improvedGlintstoneAndGravityStoneDamage" },
  7043000: { name: "improvedRoarAndBreathAttacks" },
  7043100: { name: "improvedPerfumingArts" },
  7043200: { name: "improvedStonediggerSorcery" },
  7043300: { name: "improvedCarianSwordSorcery" },
  7043400: { name: "improvedGlintbladeSorcery" },
  7043500: { name: "improvedInvisibilitySorcery" },
  7043600: { name: "improvedCrystalianSorcery" },
  7043700: { name: "improvedGravitySorcery" },
  7043800: { name: "improvedThornSorcery" },
  7043900: { name: "improvedNightSorcery" },
  7044000: { name: "improvedFundamentalistIncantations" },
  7044100: { name: "improvedDragonCultIncantations" },
  7044200: { name: "improvedGiantsFlameIncantations" },
  7044300: { name: "improvedGodslayerIncantations" },
  7044400: { name: "improvedBestialIncantations" },
  7044500: { name: "improvedFrenziedFlameIncantations" },
  7044600: { name: "improvedDragonCommunionIncantations" },
  7050000: { name: "raisedStaminaRecoveryForNearbyAlliesButNotForSelf" },
  7050100: { name: "itemsConferEffectToAllNearbyAllies" },
  7060000: { name: "attackPowerPermanentlyIncreasedForEachEvergaolPrisonerDefeated" },
  7060100: { name: "maxFpIncreasedForEachSorcerersRiseUnlocked" },
  7060200: { name: "attackPowerUpAfterDefeatingANightInvader" },
  7070000: { name: "treasureMarkedUponMap" },
  7080000: { name: "improvedAttackPowerWith3PlusDaggersEquipped" },
  7080100: { name: "improvedAttackPowerWith3PlusStraightSwordsEquipped" },
  7080200: { name: "improvedAttackPowerWith3PlusGreatswordsEquipped" },
  7080300: { name: "improvedAttackPowerWith3PlusColossalSwordsEquipped" },
  7080400: { name: "improvedAttackPowerWith3PlusCurvedSwordsEquipped" },
  7080500: { name: "improvedAttackPowerWith3PlusCurvedGreatswordsEquipped" },
  7080600: { name: "improvedAttackPowerWith3PlusKatanaEquipped" },
  7080700: { name: "improvedAttackPowerWith3PlusTwinbladesEquipped" },
  7080800: { name: "improvedAttackPowerWith3PlusThrustingSwordsEquipped" },
  7080900: { name: "improvedAttackPowerWith3PlusHeavyThrustingSwordsEquipped" },
  7081000: { name: "improvedAttackPowerWith3PlusAxesEquipped" },
  7081100: { name: "improvedAttackPowerWith3PlusGreataxesEquipped" },
  7081200: { name: "improvedAttackPowerWith3PlusHammersEquipped" },
  7081300: { name: "improvedAttackPowerWith3PlusGreatHammersEquipped" },
  7081400: { name: "improvedAttackPowerWith3PlusFlailsEquipped" },
  7081500: { name: "improvedAttackPowerWith3PlusSpearsEquipped" },
  7081700: { name: "improvedAttackPowerWith3PlusGreatSpearsEquipped" },
  7081800: { name: "improvedAttackPowerWith3PlusHalberdsEquipped" },
  7081900: { name: "improvedAttackPowerWith3PlusReapersEquipped" },
  7082000: { name: "improvedAttackPowerWith3PlusFistsEquipped" },
  7082100: { name: "improvedAttackPowerWith3PlusClawsEquipped" },
  7082200: { name: "improvedAttackPowerWith3PlusWhipsEquipped" },
  7082300: { name: "improvedAttackPowerWith3PlusColossalWeaponsEquipped" },
  7082400: { name: "improvedAttackPowerWith3PlusBowsEquipped" },
  7082500: { name: "maxFpUpWith3PlusStavesEquipped" },
  7082600: { name: "maxFpUpWith3PlusSacredSealsEquipped" },
  7082700: { name: "maxHpUpWith3PlusSmallShieldsEquipped" },
  7082800: { name: "maxHpUpWith3PlusMediumShieldsEquipped" },
  7082900: { name: "maxHpUpWith3PlusGreatshieldsEquipped" },
  7090000: { name: "defeatingEnemiesFillsMoreOfTheArtGauge" },
  7090100: { name: "defeatingEnemiesRestoresHPForAlliesButNotForSelf" },
  7090300: { name: "defeatingEnemiesNearTotemStelaRestoresHP", character: "raider" },
  7100000: { name: "criticalHitsDealHugeDamageOnPoisonedEnemies" },
  7100100: { name: "staminaRecoveryUponLandingAttacks" },
  7100110: { name: "staminaRecoveryUponLandingAttacksPlus1" },
  7100190: { name: "staminaRecoveryUponLandingAttacksPlus1" },
  7110000: { name: "increasedRuneAcquisitionForSelfAndAllies" },
  7120000: { name: "startingArmamentDealsMagicDamage" },
  7120100: { name: "startingArmamentDealsFireDamage" },
  7120101: { name: "armamentDealsFireDamagePlus1AtStartOfExpedition" },
  7120200: { name: "startingArmamentDealsLightningDamage" },
  7120300: { name: "startingArmamentDealsHolyDamage" },
  7120400: { name: "startingArmamentInflictsFrostStatus" },
  7120500: { name: "startingArmamentInflictsPoisonStatus" },
  7120600: { name: "startingArmamentInflictsBloodLossStatus" },
  7120700: { name: "startingArmamentInflictsScarletRotStatus" },
  7120900: { name: "stoneswordKeyInPossessionAtStartOfExpedition" },
  7121000: { name: "smallPouchInPossessionAtStartOfExpedition" },
  7121100: { name: "firePotsInPossessionAtStartOfExpedition" },
  7121200: { name: "magicPotsInPossessionAtStartOfExpedition" },
  7121300: { name: "lightningPotsInPossessionAtStartOfExpedition" },
  7121400: { name: "holyWaterPotsInPossessionAtStartOfExpedition" },
  7121500: { name: "poisonboneDartsInPossessionAtStartOfExpedition" },
  7121600: { name: "crystalDartsInPossessionAtStartOfExpedition" },
  7121700: { name: "throwingDaggersInPossessionAtStartOfExpedition" },
  7121800: { name: "glintstoneScrapsInPossessionAtStartOfExpedition" },
  7121900: { name: "gravityStoneChunksInPossessionAtStartOfExpedition" },
  7122000: { name: "bewitchingBranchesInPossessionAtStartOfExpedition" },
  7122100: { name: "wraithCallingBellInPossessionAtStartOfExpedition" },
  7122200: { name: "fireGreaseInPossessionAtStartOfExpedition" },
  7122300: { name: "magicGreaseInPossessionAtStartOfExpedition" },
  7122400: { name: "lightningGreaseInPossessionAtStartOfExpedition" },
  7122500: { name: "holyGreaseInPossessionAtStartOfExpedition" },
  7122600: { name: "shieldGreaseInPossessionAtStartOfExpedition" },
  7122700: { name: "changesCompatibleArmamentsSkillToGlintbladePhalanxAtStartOfExpedition" },
  7122800: { name: "changesCompatibleArmamentsSkillToGravitasAtStartOfExpedition" },
  7122900: { name: "changesCompatibleArmamentsSkillToFlamingStrikeAtStartOfExpedition" },
  7123000: { name: "changesCompatibleArmamentsSkillToEruptionAtStartOfExpedition" },
  7123100: { name: "changesCompatibleArmamentsSkillToThunderboltAtStartOfExpedition" },
  7123200: { name: "changesCompatibleArmamentsSkillToLightningSlashAtStartOfExpedition" },
  7123300: { name: "changesCompatibleArmamentsSkillToSacredBladeAtStartOfExpedition" },
  7123400: { name: "changesCompatibleArmamentsSkillToPrayerfulStrikeAtStartOfExpedition" },
  7123500: { name: "changesCompatibleArmamentsSkillToPoisonousMistAtStartOfExpedition" },
  7123600: { name: "changesCompatibleArmamentsSkillToPoisonMothFlightAtStartOfExpedition" },
  7123700: { name: "changesCompatibleArmamentsSkillToBloodBladeAtStartOfExpedition" },
  7123800: { name: "changesCompatibleArmamentsSkillToSeppukuAtStartOfExpedition" },
  7123900: { name: "changesCompatibleArmamentsSkillToChillingMistAtStartOfExpedition" },
  7124000: { name: "changesCompatibleArmamentsSkillToHoarfrostStompAtStartOfExpedition" },
  7124100: { name: "changesCompatibleArmamentsSkillToWhiteShadowsLureAtStartOfExpedition" },
  7124300: { name: "changesCompatibleArmamentsSkillToEndureAtStartOfExpedition" },
  7124400: { name: "changesCompatibleArmamentsSkillToQuickstepAtStartOfExpedition" },
  7124500: { name: "changesCompatibleArmamentsSkillToStormStompAtStartOfExpedition" },
  7124600: { name: "changesCompatibleArmamentsSkillToDeterminationAtStartOfExpedition" },
  7124700: { name: "changesCompatibleArmamentsSkillToRainOfArrowsAtStartOfExpedition" },
  7126000: { name: "starlightShardsInPossessionAtStartOfExpedition" },
  7126001: { name: "starlightShardsInPossessionAtStartOfExpedition" },
  7126002: { name: "starlightShardsInPossessionAtStartOfExpedition" },
  7150000: { name: "guardCounterIsGivenABoostBasedOnCurrentHP" },
  7160000: { name: "hpRestorationUponThrustingCounterattack" },
  7200000: { name: "hpRestorationWithHeadShots" },
  7200100: { name: "improvedStanceBreakingWithHeadShots" },
  7220000: { name: "revenantPowerUpWhileFightingAlongsideFamily", character: "revenant" },
  7230000: { name: "runeDiscountForShopPurchasesWhileOnExpedition" },
  7230001: { name: "hugeRuneDiscountForShopPurchasesWhileOnExpedition" },
  7240000: { name: "improvedPoiseDamageNegationWhenKnockedBackByDamage" },
  7260000: { name: "attackPowerUpWhenFacingPoisonAfflictedEnemy" },
  7260200: { name: "attackPowerUpWhenFacingSleepAfflictedEnemy" },
  7260300: { name: "attackPowerUpWhenFacingScarletRotAfflictedEnemy" },
  7260400: { name: "attackPowerUpWhenFacingFrostbiteAfflictedEnemy" },
  7260600: { name: "attacksCreateMagicBurstsVersusSleepingEnemies" },
  7260700: { name: "nearbyFrostbiteConcealsSelf" },
  7260710: { name: "poisonAndRotInVicinityIncreasesAttackPower" },
  7260800: { name: "poisonAndRotInVicinityIncreasesAttackPower" },
  7270100: { name: "ironeyePlus1AdditionalCharacterSkillUse", character: "ironeye" },
  7280000: { name: "ironeyeExtendsDurationOfWeakPoint", character: "ironeye" },
  7290000: { name: "duchessImprovedCharacterSkillAttackPower", character: "duchess" },
  7300000: { name: "duchessCharacterSkillInflictsSleep", character: "duchess" },
  7310000: { name: "raiderDurationOfUltimateArtExtended", character: "raider" },
  7320000: { name: "revenantAbilityActivationChanceIncreased", character: "revenant" },
  7330000: { name: "improvedDaggerAttackPower" },
  7330100: { name: "improvedStraightSwordAttackPower" },
  7330200: { name: "improvedGreatswordAttackPower" },
  7330300: { name: "improvedColossalSwordAttackPower" },
  7330400: { name: "improvedCurvedSwordAttackPower" },
  7330500: { name: "improvedCurvedGreatswordAttackPower" },
  7330600: { name: "improvedKatanaAttackPower" },
  7330700: { name: "improvedTwinbladeAttackPower" },
  7330800: { name: "improvedThrustingSwordAttackPower" },
  7330900: { name: "improvedHeavyThrustingSwordAttackPower" },
  7331000: { name: "improvedAxeAttackPower" },
  7331100: { name: "improvedGreataxeAttackPower" },
  7331200: { name: "improvedHammerAttackPower" },
  7331300: { name: "improvedGreatHammerAttackPower" },
  7331400: { name: "improvedFlailAttackPower" },
  7331500: { name: "improvedSpearAttackPower" },
  7331600: { name: "improvedPikeAttackPower" },
  7331700: { name: "improvedGreatSpearAttackPower" },
  7331800: { name: "improvedHalberdAttackPower" },
  7331900: { name: "improvedReaperAttackPower" },
  7332000: { name: "improvedFistAttackPower" },
  7332100: { name: "improvedClawAttackPower" },
  7332200: { name: "improvedWhipAttackPower" },
  7332300: { name: "improvedColossalWeaponAttackPower" },
  7332400: { name: "improvedBowAttackPower" },
  7332500: { name: "improvedGreatbowAttackPower" },
  7332600: { name: "improvedCrossbowAttackPower" },
  7332700: { name: "improvedBallistaAttackPower" },
  7340000: { name: "hpRestorationUponDaggerAttacks" },
  7340100: { name: "hpRestorationUponStraightSwordAttacks" },
  7340200: { name: "hpRestorationUponGreatswordAttacks" },
  7340300: { name: "hpRestorationUponColossalSwordAttacks" },
  7340400: { name: "hpRestorationUponCurvedSwordAttacks" },
  7340500: { name: "hpRestorationUponCurvedGreatswordAttacks" },
  7340600: { name: "hpRestorationUponKatanaAttacks" },
  7340700: { name: "hpRestorationUponTwinbladeAttacks" },
  7340800: { name: "hpRestorationUponThrustingSwordAttacks" },
  7340900: { name: "hpRestorationUponHeavyThrustingSwordAttacks" },
  7341000: { name: "hpRestorationUponAxeAttacks" },
  7341100: { name: "hpRestorationUponGreataxeAttacks" },
  7341200: { name: "hpRestorationUponHammerAttacks" },
  7341300: { name: "hpRestorationUponGreatHammerAttacks" },
  7341400: { name: "hpRestorationUponFlailAttacks" },
  7341500: { name: "hpRestorationUponSpearAttacks" },
  7341600: { name: "hpRestorationUponPikeAttacks" },
  7341700: { name: "hpRestorationUponGreatSpearAttacks" },
  7341800: { name: "hpRestorationUponHalberdAttacks" },
  7341900: { name: "hpRestorationUponReaperAttacks" },
  7342000: { name: "hpRestorationUponFistAttacks" },
  7342100: { name: "hpRestorationUponClawAttacks" },
  7342200: { name: "hpRestorationUponWhipAttacks" },
  7342300: { name: "hpRestorationUponColossalWeaponAttacks" },
  7342400: { name: "hpRestorationUponBowAttacks" },
  7342500: { name: "hpRestorationUponGreatbowAttacks" },
  7342600: { name: "hpRestorationUponCrossbowAttacks" },
  7342700: { name: "hpRestorationUponBallistaAttacks" },
  7350000: { name: "fpRestorationUponDaggerAttacks" },
  7350100: { name: "fpRestorationUponStraightSwordAttacks" },
  7350200: { name: "fpRestorationUponGreatswordAttacks" },
  7350300: { name: "fpRestorationUponColossalSwordAttacks" },
  7350400: { name: "fpRestorationUponCurvedSwordAttacks" },
  7350500: { name: "fpRestorationUponCurvedGreatswordAttacks" },
  7350600: { name: "fpRestorationUponKatanaAttacks" },
  7350700: { name: "fpRestorationUponTwinbladeAttacks" },
  7350800: { name: "fpRestorationUponThrustingSwordAttacks" },
  7350900: { name: "fpRestorationUponHeavyThrustingSwordAttacks" },
  7351000: { name: "fpRestorationUponAxeAttacks" },
  7351100: { name: "fpRestorationUponGreataxeAttacks" },
  7351200: { name: "fpRestorationUponHammerAttacks" },
  7351300: { name: "fpRestorationUponGreatHammerAttacks" },
  7351400: { name: "fpRestorationUponFlailAttacks" },
  7351500: { name: "fpRestorationUponSpearAttacks" },
  7351600: { name: "fpRestorationUponPikeAttacks" },
  7351700: { name: "fpRestorationUponGreatSpearAttacks" },
  7351800: { name: "fpRestorationUponHalberdAttacks" },
  7351900: { name: "fpRestorationUponReaperAttacks" },
  7352000: { name: "fpRestorationUponFistAttacks" },
  7352100: { name: "fpRestorationUponClawAttacks" },
  7352200: { name: "fpRestorationUponWhipAttacks" },
  7352300: { name: "fpRestorationUponColossalWeaponAttacks" },
  7352400: { name: "fpRestorationUponBowAttacks" },
  7352500: { name: "fpRestorationUponGreatbowAttacks" },
  7352600: { name: "fpRestorationUponCrossbowAttacks" },
  7352700: { name: "fpRestorationUponBallistaAttacks" },
};
